language: node_js
node_js:
  - "node"
services:
  - docker
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: test
      env:
        NODE_ENV=test
      script: "npm test"
    - stage: build and deploy
      before_script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com
      script:
        - docker build -t registry.heroku.com/$APP_NAME/web .
        - docker push registry.heroku.com/$APP_NAME/web