#!/bin/bash

IMAGE_ID=$(docker inspect registry.heroku.com/learnfront/web --format={{.Id}})
echo $IMAGE_ID
curl -n -X PATCH https://api.heroku.com/apps/learnfront/formation \
  -d '{
  "updates": [
    {
      "type": "web",
      "docker_image": "$IMAGE_ID"
    }
  ]
}' \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
  -H "Authorization: Bearer $DOCKER_PASSWORD"
